---
title: "Smash for mutation rate"
output: html_document
---

```{r setup}
library(smashr)
```
Now we consider estimating a spatially structured mean $\mu$ = ($\mu_1$, . . . , $\mu_2$ ) from Poisson data:

$$y_t ∼ Pois(\mu_t), (t = 1, . . . , T)$$
# Simulation 1
```{r smash1, fig.width = 10, fig.height=3}
n = 1000
t = 1:n
spike.f = function(x) (5 * exp(-100 * round((x - 100)/10)^2) + 5 * exp(-100 * round((x - 400)/10)^2) + 5 * exp(-100 * round((x - 800)/10)^2) + 2 * exp(-100 * round((x - 500)/100)^2) 
   )
mu.s = spike.f(t)

# POISSON CASE
# ------------
# Scale the signal to be non-zero and to have a low average intensity.
mu.t = 1 + mu.s

# Simulate an example dataset.
set.seed(101)
X.s = rpois(n, mu.t)

# Run smash.
mu.est = smash(X.s, "poiss")

# Plot the estimated mean function (red) against the ground-truth (black).
plot(mu.t, type = "l", col="darkgreen", lwd=1.5, ylab= "# mutations/window", xlab = "Genomic position (kb)", ylim=c(0,max(X.s)))
points(X.s,col="darkgreen", cex=0.2)
lines(mu.est, col = "salmon", lwd=1.5)
```
Here, green is the real parameter and data. red is the esitmated mean by smash.

# Simulation 2
```{r smash2, fig.width = 7, fig.height=4}
n = 500
t = 1:n
spike.f = function(x) ( 2 * exp(-100 * round((x - 100)/10)^2) + 2 * exp(-100 * round((x - 450)/10)^2) + 0.5 * exp(-100 * round((x - 300)/100)^2) 
   )
mu.s = spike.f(t)

# POISSON CASE
# ------------
# Scale the signal to be non-zero and to have a low average intensity.
mu.t = 1 + mu.s

# Simulate an example dataset.
set.seed(36)
X.s = rpois(n, mu.t)

# Run smash.
sm <- smash.poiss(X.s,post.var = TRUE)

# Plot the estimated mean function (red) against the ground-truth (black).
plot(mu.t, type = "l", col="#2171b5", lwd=1.5, ylab= "# mutations/window", xlab = "Genomic position (kb)", ylim=c(0,max(X.s)))
points(X.s,col="#525252", cex=0.2)
lines(sm$est, col = "salmon", lwd=1.5)
lines(sm$est+2*sqrt(sm$var),col="#fee5d9",lwd=1.5)
lines(sm$est-2*sqrt(sm$var),col="#fee5d9",lwd=1.5)
```

Here, green is the real parameter and data. red is the esitmated mean by smash.

# Apply to real data

```{r realdata}
region <- head(read.table("table.100k.window.stand.diff.cutoff.4.topwindow.across.all.mutation.type.CSV", sep=",", skip=1, stringsAsFactors = F), n=5)
dat <- read.table("table.ASCWGS_20180504.WGS1902_hg19_controls_SNV_remove_recurrent_mutation.20kwindow.csv")
for (i in 1:nrow(region)){
  dat0 <- dat[dat$chr==region[i,2] & dat$start > region[i,3] - 6e6 & dat$start < region[i,4] + 6e6, ]
  # Run smash.
  mu.est = smash(dat0$obs, "poiss")
  plot(dat0$start/1e6, dat0$obs, type = "l", col=NA, lwd=1.5, ylab= "# mutations/window", xlab = "Genomic position (Mb)", ylim=c(0,max(dat0$obs)), main = paste0(region[i,2],":",region[i,3]))
  points(dat0$start/1e6, dat0$obs, col="darkgreen", cex=0.2)
  lines(dat0$start/1e6, mu.est, col = "salmon", lwd=1.5)
}
```
One of the region is interesting and we choose it and overlay with John's data.

This is chr16: 12600000
```{r overlay}
par(mfrow=c(2,1), mar=c(1,4,2,2))
region <- head(read.table("table.100k.window.stand.diff.cutoff.4.topwindow.across.all.mutation.type.CSV", sep=",", skip=1, stringsAsFactors = F), n=5)
dat <- read.table("table.ASCWGS_20180504.WGS1902_hg19_controls_SNV_remove_recurrent_mutation.20kwindow.csv")
i <- 3
dat0 <- dat[dat$chr==region[i,2] & dat$start > 8000000 & dat$start < 17980000 , ] # to overlay with John's data
# Run smash.
sm <- smash.poiss(dat0$obs, post.var = TRUE)
plot(dat0$start/1e6 , dat0$obs, type = "l", col=NA, lwd=1.5, ylab= "# mutations/window", ylim=c(0,max(dat0$obs)), xlab=NA, xaxt='n')
points(dat0$start/1e6 , dat0$obs, col="#525252", cex=0.3,pch=19)
lines(dat0$start/1e6 , sm$est, col = "salmon", lwd=1.5)
lines(dat0$start/1e6 , sm$est+2*sqrt(sm$var),col="#fee5d9",lwd=1.5)
lines(dat0$start/1e6 , sm$est-2*sqrt(sm$var),col="#fee5d9",lwd=1.5)

par(mar=c(4,4,0,2))
dat2 <- read.table("table.chr16_8000000-18000000_20000_af1e-5_counts.bedgraph")
counts <- dat2$V4
pos <- (dat2$V2+ dat2$V3)/2
sm <- smash.gaus(counts,joint = TRUE)
plot(pos/1e6,sm$mu.res,xlab="Genomic position (Mb)",ylab="Observed counts",type="l",ylim=c(0,1.1*max(counts)),lwd=0.5)
points(pos/1e6, counts, col="#525252", cex=0.3,pch=19)
```
